### ISSUE TITLE
Treffen Nummer Drei (diesmal mit Tutor)

### ISSUE THREAD

**Issue by jakicoll** [ProPra16/programmierpraktikum-abschlussprojekt-lieblingsprojekt-1#1]
@Rob3rtK @cakas100 @taroe100 @milo101 @yoaiss

Hallo Liebe Gruppe _Lieblingsprojekt_.

Ich würde gerne an eurem dritten wöchentlichen Treffen anfangs kurz teilnehmen, um euch kennenzulernen und den aktuellen Stand zu erfahren.

Mögliche Zeiten, zu denen ich gut kann:
- Mittwoch ab 13:00 Uhr (14 Uhr wäre auch möglich).
- Donnerstag um 14 Uhr (also nach der ProPra-Vorlesung)
- Freitag zwischen 10:00 Uhr und 12:00 Uhr sowie um 12:30 Uhr.

Andere Termine sind ggf. auch möglich.
Bitte gebt mir möglichst bald eine Rückmeldung.

Viele Grüße,

Jakob Scheumann
Korrektor/Tutor Programmierpraktikum

**Comment by Rob3rtK** [comment]
Hallo Jakob,

Blocke dir mal bitte die Zeit am Donnerstag um 14 Uhr. Einen Raum werde ich dir noch bekannt geben wo wir uns treffen.

Viele Grüße und bis Donnerstag,
Robert

**Comment by jakicoll** [comment]
Hallo Robert.

Genau um :clock2: trifft sich auch eine andere Gruppe, die ich betreuue. Ich komme also ggf. etwas später dazu. Das ist glaube ich vernünftiger als mit allen Beteiligten neue Termine zu finden. :smirk:

Den Raum bitte einfach hier dazuschreiben.

Grüße,

Jakob

**Comment by Rob3rtK** [comment]
Hey Jakob,

Kannst zu uns in der Verbundbib dazustoßen, Raum 8.

VG
Robert
