### ISSUE TITLE
Commits von "ijijio@uiuj.de"

### ISSUE THREAD

**Issue by jakicoll** [ProPra16/programmierpraktikum-abschlussprojekt-lieblingsprojekt-1#2]
Hallo @ProPra16/lieblingsprojekt 

Jemand hat lokal in seiner Git-Konfiguration als eMail-Adresse _ijijio@uiuj.de_ angegeben. Da ich diese Commits gerne einem von euch zuordnen würde, bitte ich daraum, bescheid zu geben, von wem sie sind. Außerdem bitte die Adresse via 

``` BASH
git config user.email
```

auf die Adresse zu ändern, mit der ihr euch bei github angemeldet habt!

**Comment by Rob3rtK** [comment]
Hallo @jakicoll 
leider kann ich nicht in dedn Commits sehen wer das gepusht hat. Kannst du mir bitte die ID des Commits geben.

Danke und Grüße,
Robert

**Comment by jakicoll** [comment]
Das wären
- aa381039c388acf41724ac1e9d45264994902094
- 44d02742d5297e40e17b14746c4e958085034fb6
- 3a1d4aaaca4a241213f547dbc0a5a1f0669ba3bb
- fc4fc2176e201f1f5b25a35174979f39645562aa

**Comment by Rob3rtK** [comment]
das ist der Youssef :)
