### ISSUE TITLE
Visulisierung des TDD-Prozesses

### ISSUE THREAD

**Issue by jakicoll** [ProPra16/programmierpraktikum-abschlussprojekt-lieblingsprojekt-1#5]
@ProPra16/lieblingsprojekt 
### Frist

Bitte denkt daran, dass euer Projekt zum Abgabetermin abgeschlossen sein muss. Weiteres Nachbessern kann es nur in begründeten Ausnahmefällen geben.
### Visualisierung

In der Projektbeschreibung steht:

> Der TDD Prozess wird in irgendeiner Form visuell dargestellt. Der Nutzer soll zu jedem
> Zeitpunkt wissen, was zu tun ist, d.h., es muss klar sein, ob ein Test oder eine Klasse
> geändert werden soll und wie der Gesamtprozess aussieht.

Euer Programm soll Intuitiv benutzbar sein und mit (A)TDD unvertrauten Programmierer*innen helfen, diese Methode zu erlernen. Vielleich habt ihr eine Idee, wie ihr den Gesamtprozess (der ja gerade bei ATTD nicht ganz trivial ist) in eurer Anwendung übersichtlich darstellen könnt und den aktuellen Schritt dabei hervorheben?

**Comment by cakas100** [comment]
Hi @jakicoll,
vielen Dank für den Tipp. Wir werden schauen, was wir da noch visuell ausbessern können. :) 

VG Caro

**Comment by Rob3rtK** [comment]
Visulaaisierung wurde durch Labels noch verstärkt
